### ISSUE TITLE
Question of the webpack.conf Rules.enforce

### ISSUE THREAD

**Issue by JackieLs** [blade254353074/multi-vue#1]
[Rules.enforce](https://webpack.js.org/configuration/module/#rule-enforce)

- pre
- post
- normal
- inline  大概理解是css-loader? sass!postcss-loader这叫inline

分别是什么意思？应如何使用？文档中说

> Inline loaders and ! prefixes should not be used as they are non-standard. They may be use by loader generated code.

尽量不要这样用吗？

**Comment by blade254353074** [comment]
`pre` 和 `post` 代表「预先」和「随后」。

inline 和 `!` 就是你说的那种，一般在 JS 中直接用 `require` 使用，使用很灵活，但是我觉得会造成配置的割裂，不好维护，所以官方也就将其列为「非标准」，不推荐使用。

**Comment by JackieLs** [comment]
pre预先加载loader，post随后加载loader。我觉得随后加载的这个几乎没什么用啊？大多数情况不都是预先加载么？

**Comment by blade254353074** [comment]
不是加载，是处理……
比如你要用 standard-loader 做代码检查，可以写成：

```javascript
{
  test: /\.jsx?$/i,
  use: [{
    loader: 'babel-loader',
    options: { cacheDirectory: true }
  }, {
    loader: 'standard-loader'
  }]
}
```

也可以写成：

```javascript
{
  test: /\.jsx?$/i,
  loader: 'standard-loader'
}, {
  test: /\.jsx?$/i,
  loader: 'babel-loader',
  options: { cacheDirectory: true }
}
```

后者职责更分明。

**Comment by JackieLs** [comment]
soga...get了。
